## Environment

# Environment Variables for MangoWM
env=XCURSOR_SIZE,18
env=XCURSOR_THEME,Vimix-cursors
env=BROWSER,helium-browser-bin
env=DE,generic

# Nvidia
env=LIBVA_DRIVER_NAME,nvidia
env=__GLX_VENDOR_LIBRARY_NAME,nvidia

# Qt/Wayland
env=QT_QPA_PLATFORM,wayland
env=QT_QPA_PLATFORMTHEME,gtk3
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# XDG
env=XDG_SESSION_TYPE,wayland
env=XDG_CURRENT_DESKTOP,mango
env=XDG_SESSION_DESKTOP,mango
env=XDG_PICTURES_DIR,/home/rhosm/Pictures/Screenshots

# Other
env=GDK_BACKEND,wayland,x11
env=ELECTRON_OZONE_PLATFORM_HINT,auto

## Output
# AOC Q27B35E
monitorrule=serial:2S6R6HA008726,x:0,y:0,scale:1.0,rr:0

# ASUS VP278
monitorrule=serial:GBLMTF073880,x:2560,y:0,scale:1.0,rr:0

