## Input

# Keyboard Settings
numlockon=1
xkb_rules_layout=us
xkb_rules_variant=altgr-intl

# Tablet
devicerule=type:tablet,monitor:serial:2S6R6HA008726
devicerule=type:pad,monitor:serial:2S6R6HA008726
