## Layouts
# General
circle_layout=dwindle,scroller,tile
tagrule=id:*,layout_name:dwindle

# Overview
enable_hotarea=1
hotarea_corner=2
overviewgappo=8

# Scroller
scroller_default_proportion=0.5
scroller_focus_center=1
scroller_proportion_preset=1.0,0.9,0.5,0.33
scroller_structs=0
scroller_ignore_proportion_single=0
scroller_default_proportion_single=1.0
