## Window rules
# Opacity rules go in a sepate section, all other rules arranged by application

# Helium Browser (tag, monitor)
windowrule=tags:1,monitor:serial:2S6R6HA008726,appid:helium

# Zen Browser (tag, monitor)
windowrule=tags:1,monitor:serial:2S6R6HA008726,appid:zen

# Discord (tag, monitor)
windowrule=tags:1,monitor:serial:GBLMTF073880,appid:discord

# Steam(tag, monitor, floating friends list)
windowrule=tags:2,monitor:serial:2S6R6HA008726,appid:steam
windowrule=isfloating:1,width:300,height:800,appid:^steam$,title:^Friends List$

# Games ((tag, monitor, full)
windowrule=tags:2,isfullscreen:1,appid:^steam_app_.*

# Krita (tag, monitor, floating)
windowrule=tags:3,monitor:serial:2S6R6HA008726,appid:krita
windowrule=isfloating:1,appid:^krita$,title:(Docker|Palette|Brush).*

# Google Chrome (tag, monitor)
windowrule=tags:2,monitor:serial:GBLMTF073880,appid:google-chrome

# Noctalia (floating)
windowrule=isfloating:1,appid:dev.noctalia.Noctalia

# GNOME Calendar (top-right position, floating)
windowrule=isfloating:1,offsetx:100,offsety:-100,appid:^org\.gnome\.Calendar$

# Pavucontrol (top-left position, floating)
windowrule=isfloating:1,offsetx:-100,offsety:-100,appid:^org\.pulseaudio\.pavucontrol$

# Input Remapper (floating)
windowrule=isfloating:1,appid:^input-remapper-gtk$

# Policykit (floating)
windowrule=isfloating:1,appid:^lxqt-policykit-agent$

# Foot (floating, size)
windowrule=isfloating:1,width:1600,height:1000,appid:foot

# Ghostty (floating, size)
windowrule=isfloating:1,width:1600,height:1000,appid:com.mitchellh.ghostty

# Kitty (floating, size)
windowrule=isfloating:1,width:1600,height:1000,appid:kitty

# Waypaper (floating, size)
windowrule=isfloating:1,width:1600,height:1000,appid:waypaper

# Nautilus (floating)
windowrule=isfloating:1,appid:nautilus,title:File Operation Progress

# Opacity Exceptions
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:io.github.celluloid_player.Celluloid
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:foundryvtt
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:org.gnome.Loupe
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:krita
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:zen,title:.*YouTube.*
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:helium,title:.*YouTube.*
windowrule=focused_opacity:0.8,unfocused_opacity:0.8,appid:foot
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:com.mitchellh.ghostty
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:kitty
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:waypaper
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:^steam_app_.*
